Repository answer0424/FITPLE_frontend, pull requests merged in 2025-02, with the labels that each got.

#17 Quiz page component
  fitple/.env
  fitple/src/Fitple.jsx
  fitple/src/mainpage/apis/api.js
  fitple/src/mainpage/components/RegisterForm.jsx
  fitple/src/quizpage/components/ui/ResultModal.jsx
  fitple/src/quizpage/pages/QuizPage.jsx
  fitple/src/quizpage/pages/QuizResult.jsx
Labels: ✨Feat

#26 Quiz page models
  fitple/.gitignore
  fitple/package-lock.json
  fitple/package.json
Labels: 👷Struct

#29 Feat(#4): quiz result design 완
  fitple/src/quizpage/pages/QuizResult.css
  fitple/src/quizpage/pages/QuizResult.jsx
Labels: ✨Feat

#31 Quiz page component
  fitple/package-lock.json
  fitple/package.json
  fitple/src/Fitple.jsx
  fitple/src/assets/chatIcon.png
  fitple/src/common/component/ChatIcon.jsx
  fitple/src/common/component/ChatMessage.jsx
  fitple/src/common/component/ChatModal.jsx
  fitple/src/common/component/Footer.jsx
  fitple/src/common/component/Header.jsx
  fitple/src/common/css/ChatIcon.css
  fitple/src/common/css/ChatMessage.css
  fitple/src/common/css/ChatModal.css
  fitple/src/common/css/Footer.css
  fitple/src/common/css/Header.css
  fitple/src/index.css
  fitple/src/main.jsx
  fitple/src/mainpage/apis/auth.js
  fitple/src/mainpage/apis/chat.js
  fitple/src/mainpage/assets/images/MainPageBackgroundImg.png
  fitple/src/mainpage/assets/images/MainPageBackgroundImgDeco.png
  fitple/src/mainpage/assets/images/sectionImg.png
  fitple/src/mainpage/assets/styles/MainPage.css
  fitple/src/mainpage/contexts/LoginContextProvider.jsx
  fitple/src/mainpage/pages/LoginPage.jsx
  fitple/src/mainpage/pages/MainPage.jsx
  fitple/src/quizpage/components/base/QuizComponent.jsx
Labels: ✨Feat

#34 Quiz page component
  fitple/package-lock.json
  fitple/src/main.jsx
  fitple/src/mainpage/pages/LoginPage.jsx
  fitple/src/quizpage/components/ui/PanelNavigation.css
  fitple/src/quizpage/components/ui/PanelNavigation.jsx
  fitple/src/quizpage/components/ui/ResultModal.css
  fitple/src/quizpage/pages/QuizPage.jsx
  fitple/src/quizpage/pages/QuizResult.jsx
Labels: ✨Feat

#38 Refactor(): component logincontextprovider 적용
  fitple/src/Fitple.jsx
  fitple/src/HBTIpage/dummypage.txt
  fitple/src/common/component/ProtectedRoute.jsx
  fitple/src/mainpage/contexts/LoginContextProvider.jsx
  fitple/src/mainpage/pages/LoginPage.jsx
  fitple/src/mainpage/pages/MainPage.jsx
  fitple/src/quizpage/components/ui/ResultModal.jsx
  fitple/src/quizpage/pages/QuizPage.jsx
Labels: ✍️Refactor

#39 Chat page
  fitple/src/common/component/ChatMessage.jsx
  fitple/src/common/component/ChatModal.jsx
  fitple/src/common/css/ChatMessage.css
  fitple/src/common/css/Footer.css
  fitple/src/mainpage/apis/chat.js
  fitple/src/mainpage/assets/styles/MainPage.css
  fitple/src/mainpage/contexts/LoginContextProvider.jsx
Labels: ✨Feat

#44 Quiz page component
  fitple/src/quizpage/pages/QuizResult.jsx
Labels: ✨Feat

#48 Admin page
  fitple/src/Fitple.jsx
  fitple/src/adminpage/apis/admin.js
  fitple/src/adminpage/components/ReviewList.jsx
  fitple/src/adminpage/components/TrainerList.jsx
  fitple/src/adminpage/components/UserList.jsx
  fitple/src/adminpage/pages/AdminPage.jsx
  fitple/src/adminpage/pages/admin.css
  fitple/src/common/component/ProtectedRoute.jsx
  fitple/src/mainpage/contexts/LoginContextProvider.jsx
  fitple/src/mypage/pages/MyPage.jsx
Labels: ✨Feat

#50 Feat(#42): adminpage logincontextprovider 수정
  fitple/src/mainpage/contexts/LoginContextProvider.jsx
  fitple/src/mypage/pages/MyPage.jsx
Labels: 🐛Fix

#51 Feat(#42): D 완료
  fitple/src/adminpage/components/TrainerList.jsx
  fitple/src/adminpage/components/UserList.jsx
  fitple/src/mypage/pages/MyPage.jsx
Labels: ✨Feat

#53 Feat(#7): css 완
  fitple/src/HBTIpage/component/css/HBTIListDetailPage.css
  fitple/src/HBTIpage/pages/HBTIListDetailPage.jsx
Labels: ✨Feat

#54 Feat(): home alert
  fitple/src/HBTIpage/component/css/HBTIListDetailPage.css
  fitple/src/HBTIpage/pages/HBTIListDetailPage.jsx
  fitple/src/quizpage/components/ui/UIOverlay.jsx
Labels: ✨Feat
